hotwax/launchpad

- src/views/Home.vue
> Added styling for app

- src/main.ts
> Improved: mode for ionic to md

- .env
- package-lock.json
- package.json
- src/App.vue
- src/adapter/index.ts
- src/event-bus/index.ts
- src/locales/en.json
- src/main.ts
- src/services/UserService.ts
- src/store/auth.ts
- src/views/Home.vue
- src/views/Login.vue
> Implemented: logic for login flow

- src/views/Home.vue
> Added: token and oms info in the app links

- .env.example
- src/router/index.ts
- src/views/Home.vue
- src/views/Login.vue
> Implemented: login guard and prefill oms on login

- src/views/Login.vue
> Fixed: SAML api failure and handled invalid credential use case

- src/views/Login.vue
> Fixed: handling for redirect URL in case of SAML login

- src/locales/en.json
- src/views/Login.vue
> Improved: hide background for confirm alert and processing loader

- src/views/Login.vue
> Fixed: empty screen when navigating from home to login using logout

- src/views/Login.vue
> Implemented: go to apps button in login page (#38)

- src/views/Login.vue
> Implemented: show OMS input on logout from app and launchpad if SAML is configured (#44)

- src/views/Login.vue
> Fixed: fetchLoginOptions failing if OMS is not found in state (#44)

- package-lock.json
- package.json
- src/App.vue
- src/adapter/index.ts
- src/services/UserService.ts
- src/store/auth.ts
- src/views/Login.vue
Related Issue: https://github.com/hotwax/dxp-components/issues/144
> Implemented: support for single logout

- src/views/Login.vue
> Fixed: SAML redirection error in case of unconfigured OMS (checkLoginOptions not available on the instance) (#44)

- src/views/Login.vue
Closes #43
Preventing the form to submit using @submit.prevent in form element.
> Fixed: Enter function not working after OMS input (#43)

- src/views/Home.vue
Closes #65
Created an entry for User Managment app in a new category "Administration"
> Implemented: user management app entry in Administration category (#65)

- package-lock.json
- package.json
> Improved: app version in package and lock file for major release(v2.0.0)

- .github/workflows/firebase-hosting-merge.yml
Closes #
Updated: Changed firebase hosting on merge to deploy launchpad dev instance instead of launchpad production instance.
> Updated: Changed firebase hosting on merge to deploy launchpad dev instance instead of launchpad production instance.

- .firebaserc
- firebase.json
Closes #
Improved: Changed naming in firebase deployment config.
> Improved: Changed naming in firebase deployment config.

- src/views/Home.vue
> Fixed: redirection to app after navigating to home screen and then logging in (#70)

- package-lock.json
- package.json
> Updated: app version for minor release(v2.1.0)

- .gitignore
> Improved: gitignore file

- src/views/Login.vue
> Fixed: issue when samlLogin flow fails, redirecting the user to login page

- src/main.ts
#82 
- Added a entry in `main` file to fix html tags not working in the translations.
> Fixed: html tags not working in the translations (#82)

- src/views/Login.vue
> Fixed: case in login to not redirect the user to any app if the user is coming from the oms

- src/store/auth.ts
Related Issue #109 
When logout api rejects the promise then the flow halts, so added check to continue the logout process even when the promise rejects
> Fixed: code to handle the case when logout promise rejects(#109)

- .env.example
- src/assets/images/Company.svg
- src/views/Home.vue
Related Issue #115
Added Company app entry in the launchpad home page.
> Improved: added entry for the Company app in dashboard (#115)

- src/util/index.ts
- src/views/Home.vue
#
Added support to use different login flow for same app's instance(dev, uat or production) but updating the condition to check on the app environment.
> Implemented: support to use different login flow for the same app's instance

- .env.example
#
Added users and job-manager app entry in the env for the login with maarg.
> Improved: added entry in env for users and job-manager app for the oms with maarg app

- package-lock.json
- package.json
> Updated: app version for minor release v3.1.0

- src/views/Home.vue
> Improved: home page to include transfers app card(#137)

- package-lock.json
- package.json
> Updated: app version for minor release (v3.1.0)

- package-lock.json
- package.json
> Updated: app version for minor release (v3.2.0)

- .env.example
> Improved: Added receiving app entry in oms with maarg.

- package-lock.json
- package.json
> Updated: app version for minor release v3.3.0

- src/util/index.ts
- src/views/Home.vue
- src/views/Login.vue
> Improved: code to handle the app link creation(legacy or new) based on permissions when redirecting from login page

- package-lock.json
- package.json
> Updated: app version for minor release v3.4.0

- src/store/auth.ts
- src/views/Login.vue
> Improved: code to fetch the permissions when moving through saml login

- package-lock.json
- package.json
> Updated: app version for patch release v3.4.1

- package-lock.json
- package.json
> Updated: app version for path release v3.4.2

- src/util/index.ts
> Removed: picking app entry from launchpad(#164)

- package-lock.json
- package.json
> Updated: app version for minor release v3.5.0
